//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.nmtinstaller.csi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.nmtinstaller.csi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed an application, below this text may appear some
        ///instructions how to start using the application..
        /// </summary>
        internal static string DoneInstalling_Application {
            get {
                return ResourceManager.GetString("DoneInstalling_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed a custom menu, please use the &quot;SOURCE&quot; button
        ///on your remote control and select HARD_DISK for the settings to
        ///take effect..
        /// </summary>
        internal static string DoneInstalling_CustomMenu {
            get {
                return ResourceManager.GetString("DoneInstalling_CustomMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed a custom menu, please reboot for the settings to
        ///take effect..
        /// </summary>
        internal static string DoneInstalling_CustomMenuA4 {
            get {
                return ResourceManager.GetString("DoneInstalling_CustomMenuA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed a theme, please restart the NMT
        ///for the settings to take effect..
        /// </summary>
        internal static string DoneInstalling_Theme {
            get {
                return ResourceManager.GetString("DoneInstalling_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed a new wait image set.
        ///Thank you for using NMT Community Software Installer..
        /// </summary>
        internal static string DoneInstalling_WaitImageSet {
            get {
                return ResourceManager.GetString("DoneInstalling_WaitImageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed a new webservice.
        ///Open main menu on your NMTand choose Web services.
        ///Your newly added webservice should be located in there..
        /// </summary>
        internal static string DoneInstalling_Webservice {
            get {
                return ResourceManager.GetString("DoneInstalling_Webservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open NMT Application zip.
        /// </summary>
        internal static string FileDialog_OpenAppZipCaption {
            get {
                return ResourceManager.GetString("FileDialog_OpenAppZipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMT Application (*.zip)|*.zip.
        /// </summary>
        internal static string FileDialog_OpenAppZipFilter {
            get {
                return ResourceManager.GetString("FileDialog_OpenAppZipFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save screenshot.
        /// </summary>
        internal static string FileDialog_SaveScreenshotCaption {
            get {
                return ResourceManager.GetString("FileDialog_SaveScreenshotCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG files (*.jpg)|*.jpg.
        /// </summary>
        internal static string FileDialog_SaveScreenshotFilter {
            get {
                return ResourceManager.GetString("FileDialog_SaveScreenshotFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select firmware ZIP file.
        /// </summary>
        internal static string FileDialog_SelectFirmwareFileCaption {
            get {
                return ResourceManager.GetString("FileDialog_SelectFirmwareFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware file (*.zip)|*.zip.
        /// </summary>
        internal static string FileDialog_SelectFirmwareFileFilter {
            get {
                return ResourceManager.GetString("FileDialog_SelectFirmwareFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string InstallItem_ApplicationString {
            get {
                return ResourceManager.GetString("InstallItem_ApplicationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom menu.
        /// </summary>
        internal static string InstallItem_IndexString {
            get {
                return ResourceManager.GetString("InstallItem_IndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a CSI installer package file (zip).
        /// </summary>
        internal static string InstallItem_Package {
            get {
                return ResourceManager.GetString("InstallItem_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string InstallItem_ThemeString {
            get {
                return ResourceManager.GetString("InstallItem_ThemeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait image set.
        /// </summary>
        internal static string InstallItem_WaitImageSetString {
            get {
                return ResourceManager.GetString("InstallItem_WaitImageSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice.
        /// </summary>
        internal static string InstallItem_WebserviceString {
            get {
                return ResourceManager.GetString("InstallItem_WebserviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoLarge {
            get {
                object obj = ResourceManager.GetObject("LogoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string MessageBox_AdvancedSettingsCaption {
            get {
                return ResourceManager.GetString("MessageBox_AdvancedSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! WARNING !! WARNING !! WARNING !!
        ///
        ///Only change these options if you were told to do so..
        /// </summary>
        internal static string MessageBox_AdvancedSettingsWarning {
            get {
                return ResourceManager.GetString("MessageBox_AdvancedSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application updates are available.
        ///Please check Update tab..
        /// </summary>
        internal static string MessageBox_ApplicationUpdatesAvailable {
            get {
                return ResourceManager.GetString("MessageBox_ApplicationUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates available.
        /// </summary>
        internal static string MessageBox_ApplicationUpdatesAvailableCaption {
            get {
                return ResourceManager.GetString("MessageBox_ApplicationUpdatesAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMT Cleanup.
        /// </summary>
        internal static string MessageBox_CleanCaption {
            get {
                return ResourceManager.GetString("MessageBox_CleanCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean or restart action.
        /// </summary>
        internal static string MessageBox_CleanupActionCaption {
            get {
                return ResourceManager.GetString("MessageBox_CleanupActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen action failed, most likely because of a connection problem..
        /// </summary>
        internal static string MessageBox_CleanupActionFailed {
            get {
                return ResourceManager.GetString("MessageBox_CleanupActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Networked Media Tank should be
        ///restarting shortly.
        ///Follow instructions on NMT after restart..
        /// </summary>
        internal static string MessageBox_CleanupActionSuccess {
            get {
                return ResourceManager.GetString("MessageBox_CleanupActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! WARNING !! WARNING !! WARNING !!
        ///
        ///You are about to cleanup your NMT.
        ///All default applications will be reinstalled, all customizations removed.
        ///After reboot you will be offered to do a TYPICAL or FRESH setup.
        ///A typical setup will keep your Media files while a fresh setup will do a complete wipe of your HDD.
        ///Using this option IS COMPLETELY AT OWN RISK!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string MessageBox_CleanWarning {
            get {
                return ResourceManager.GetString("MessageBox_CleanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed, please report this problem in Help or Report a bug.
        /// </summary>
        internal static string MessageBox_CsiUpdateFailed {
            get {
                return ResourceManager.GetString("MessageBox_CsiUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string MessageBox_CsiUpdateNoneAvailable {
            get {
                return ResourceManager.GetString("MessageBox_CsiUpdateNoneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSI Update.
        /// </summary>
        internal static string MessageBox_CsiUpdatesCaption {
            get {
                return ResourceManager.GetString("MessageBox_CsiUpdatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom menu delete.
        /// </summary>
        internal static string MessageBox_CustomMenuDeleteCaption {
            get {
                return ResourceManager.GetString("MessageBox_CustomMenuDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the custom menu on
        ///the Network Media Tank.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string MessageBox_CustomMenuDeleteConfirm {
            get {
                return ResourceManager.GetString("MessageBox_CustomMenuDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom menu deleted.
        ///Please use &quot;SOURCE&quot; button on remote control and select HARD_DISK
        ///for the settings to take effect..
        /// </summary>
        internal static string MessageBox_CustomMenuDeleted {
            get {
                return ResourceManager.GetString("MessageBox_CustomMenuDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while removing custom menu folder.
        ///Custom menu cleanup not completed.
        ///Please retry..
        /// </summary>
        internal static string MessageBox_CustomMenuDeleteFailed {
            get {
                return ResourceManager.GetString("MessageBox_CustomMenuDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMT DEEP Cleanup.
        /// </summary>
        internal static string MessageBox_DeepCleanCaption {
            get {
                return ResourceManager.GetString("MessageBox_DeepCleanCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! WARNING !! WARNING !! WARNING !!
        ///
        ///You are about to perform a DEEP CLEAN of your NMT.
        ///All default applications will be reinstalled, all customizations removed.
        ///After reboot you will be offered to do a TYPICAL or FRESH setup.
        ///A typical setup will keep your Media files while a fresh setup will do a complete wipe of your HDD.
        ///
        ///A DEEP CLEAN WILL REMOVE ANY NON-DEFAULT FOLDERS AND ALL SETTINGS FILES FROM YOU NMT.
        ///
        ///ALL FOLDERS AND FILES WILL BE REMOVED, EXCEPT THE FOLLOWING FOLDERS: Download, Music, Ph [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageBox_DeepCleanWarning {
            get {
                return ResourceManager.GetString("MessageBox_DeepCleanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download application.
        /// </summary>
        internal static string MessageBox_DownloadPackageCaption {
            get {
                return ResourceManager.GetString("MessageBox_DownloadPackageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to download installation files.
        ///Please check you internet connection.
        ///Try again, if problem remains please use Help menu, then use Help item
        ///and report problem there..
        /// </summary>
        internal static string MessageBox_DownloadPackageFailed {
            get {
                return ResourceManager.GetString("MessageBox_DownloadPackageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP connection test.
        /// </summary>
        internal static string MessageBox_FtpConnectionTestCaption {
            get {
                return ResourceManager.GetString("MessageBox_FtpConnectionTestCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect Network Media Tank FTP server.
        ///Make sure FTP server is enabled.
        ///Check server settings and retry..
        /// </summary>
        internal static string MessageBox_FtpConnectionTestFailed {
            get {
                return ResourceManager.GetString("MessageBox_FtpConnectionTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to shutdown the NMT, are you sure?.
        /// </summary>
        internal static string MessageBox_HaltWarning {
            get {
                return ResourceManager.GetString("MessageBox_HaltWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMT Shutdown.
        /// </summary>
        internal static string MessageBox_HaltWarningCaption {
            get {
                return ResourceManager.GetString("MessageBox_HaltWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error while trying to connect to Networked Media Tank.
        ///Please check server settings in &quot;Server/Hardware settings&quot; in Extra menu. Also make sure you have the FTP server running.
        ///
        ///If problem remains use &quot;Report a bug&quot; or &quot;Help&quot; in Help menu..
        /// </summary>
        internal static string MessageBox_InstallActionFailed {
            get {
                return ResourceManager.GetString("MessageBox_InstallActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        internal static string MessageBox_InstallationActionCaption {
            get {
                return ResourceManager.GetString("MessageBox_InstallationActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install firmware.
        /// </summary>
        internal static string MessageBox_InstallFirmwareCaption {
            get {
                return ResourceManager.GetString("MessageBox_InstallFirmwareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing new firmware failed, most likely because of a connection problem..
        /// </summary>
        internal static string MessageBox_InstallFirmwareFailed {
            get {
                return ResourceManager.GetString("MessageBox_InstallFirmwareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to reinstall or upgrading your NMT&apos;s firmware.
        ///Before you continue you need to download the firmware zip
        ///file from your NMT manufacturer&apos;s website.
        ///After you downloaded the zip file you can continue reinstalling or upgrading your firmware.
        ///UPGRADING FIRMWARE IS COMPLETELY AT OWN RISK!
        ///
        ///Are you sure you want to continue reinstalling or upgrading your firmware?.
        /// </summary>
        internal static string MessageBox_InstallFirmwareWarning {
            get {
                return ResourceManager.GetString("MessageBox_InstallFirmwareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install from file.
        /// </summary>
        internal static string MessageBox_InstallFromFileCaption {
            get {
                return ResourceManager.GetString("MessageBox_InstallFromFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a supported ZIP file format, aborting.
        /// </summary>
        internal static string MessageBox_InstallFromFileInvalidZIP {
            get {
                return ResourceManager.GetString("MessageBox_InstallFromFileInvalidZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found errors in the repository information.
        ///Please fix problems and try again.
        ///.
        /// </summary>
        internal static string MessageBox_RepositoryInfoInvalid {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryInfoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository errors.
        /// </summary>
        internal static string MessageBox_RepositoryInfoInvalidCaption {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryInfoInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart suggested.
        /// </summary>
        internal static string MessageBox_RepositoryRestartCaption {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryRestartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSI needs to be restarted to update the repository information.
        ///Restart CSI now?.
        /// </summary>
        internal static string MessageBox_RepositoryRestartConfirm {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryRestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save or cancel the changes first.
        /// </summary>
        internal static string MessageBox_RepositorySaveCancel {
            get {
                return ResourceManager.GetString("MessageBox_RepositorySaveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save or cancel.
        /// </summary>
        internal static string MessageBox_RepositorySaveCancelCaption {
            get {
                return ResourceManager.GetString("MessageBox_RepositorySaveCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository update.
        /// </summary>
        internal static string MessageBox_RepositoryUpdate {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid repository file ({0}) detected, skipping. Please report this by using &quot;Report a bug&quot; in the Help menu..
        /// </summary>
        internal static string MessageBox_RepositoryUpdateFileInvalid {
            get {
                return ResourceManager.GetString("MessageBox_RepositoryUpdateFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to repository server {0}.
        ///Make sure your internet connection is up, perhaps {0}&apos;s server is down..
        /// </summary>
        internal static string MessageBox_RepsitoryUpdateCantConnect {
            get {
                return ResourceManager.GetString("MessageBox_RepsitoryUpdateCantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMT Restart.
        /// </summary>
        internal static string MessageBox_RestartNMTCaption {
            get {
                return ResourceManager.GetString("MessageBox_RestartNMTCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to restart your Networked Media Tank
        ///Are you sure?.
        /// </summary>
        internal static string MessageBox_RestartNMTConfirm {
            get {
                return ResourceManager.GetString("MessageBox_RestartNMTConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme delete.
        /// </summary>
        internal static string MessageBox_ThemeDeleteCaption {
            get {
                return ResourceManager.GetString("MessageBox_ThemeDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the custom theme on
        ///the Network Media Tank.
        ///Are you sure?.
        /// </summary>
        internal static string MessageBox_ThemeDeleteConfirm {
            get {
                return ResourceManager.GetString("MessageBox_ThemeDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom theme deleted.
        ///Please restart Network Media Tank for the settings to take effect.
        /// </summary>
        internal static string MessageBox_ThemeDeleted {
            get {
                return ResourceManager.GetString("MessageBox_ThemeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while cleaning Theme folder.
        ///Theme cleanup not completed.
        ///Please retry..
        /// </summary>
        internal static string MessageBox_ThemeDeleteFailed {
            get {
                return ResourceManager.GetString("MessageBox_ThemeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application uninstall.
        /// </summary>
        internal static string MessageBox_UninstallCaption {
            get {
                return ResourceManager.GetString("MessageBox_UninstallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall {0}?
        ///All application and configuration files will be deleted.
        /// </summary>
        internal static string MessageBox_UninstallConfirm {
            get {
                return ResourceManager.GetString("MessageBox_UninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Images Set delete.
        /// </summary>
        internal static string MessageBox_WaitImageDeleteCaption {
            get {
                return ResourceManager.GetString("MessageBox_WaitImageDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the custom wait image set on
        ///the Network Media Tank.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string MessageBox_WaitImageDeleteConfirm {
            get {
                return ResourceManager.GetString("MessageBox_WaitImageDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Image Set is deleted, please restart the NMT for the settings to take effect..
        /// </summary>
        internal static string MessageBox_WaitImageDeleted {
            get {
                return ResourceManager.GetString("MessageBox_WaitImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while removing Wait Image Set folder.
        ///Wait Image Set cleanup not completed.
        ///Please retry..
        /// </summary>
        internal static string MessageBox_WaitImageDeleteFailed {
            get {
                return ResourceManager.GetString("MessageBox_WaitImageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoScreenshots {
            get {
                object obj = ResourceManager.GetObject("NoScreenshots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NZBVortex {
            get {
                object obj = ResourceManager.GetObject("NZBVortex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server and Hardware settings.
        /// </summary>
        internal static string PanelTitel_ServerSettings {
            get {
                return ResourceManager.GetString("PanelTitel_ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced System Settings.
        /// </summary>
        internal static string PanelTitle_Advsettings {
            get {
                return ResourceManager.GetString("PanelTitle_Advsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string PanelTitle_ChangeLanguage {
            get {
                return ResourceManager.GetString("PanelTitle_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSI update available.
        /// </summary>
        internal static string PanelTitle_CSIUpgrade {
            get {
                return ResourceManager.GetString("PanelTitle_CSIUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage instructions.
        /// </summary>
        internal static string PanelTitle_Done {
            get {
                return ResourceManager.GetString("PanelTitle_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install from file.
        /// </summary>
        internal static string PanelTitle_InstallFromZip {
            get {
                return ResourceManager.GetString("PanelTitle_InstallFromZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install results.
        /// </summary>
        internal static string PanelTitle_InstallResult {
            get {
                return ResourceManager.GetString("PanelTitle_InstallResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage repositories.
        /// </summary>
        internal static string PanelTitle_Repositories {
            get {
                return ResourceManager.GetString("PanelTitle_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired item.
        /// </summary>
        internal static string PanelTitle_SelectApplication {
            get {
                return ResourceManager.GetString("PanelTitle_SelectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server and Hardware settings.
        /// </summary>
        internal static string PanelTitle_ServerSettings {
            get {
                return ResourceManager.GetString("PanelTitle_ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and install.
        /// </summary>
        internal static string PanelTitle_UploadApplication {
            get {
                return ResourceManager.GetString("PanelTitle_UploadApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom Webservice.
        /// </summary>
        internal static string PanelTitle_Webservice {
            get {
                return ResourceManager.GetString("PanelTitle_Webservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to NMT Community Software Installer.
        /// </summary>
        internal static string PanelTitle_Welcome {
            get {
                return ResourceManager.GetString("PanelTitle_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaypalDonate {
            get {
                object obj = ResourceManager.GetObject("PaypalDonate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Text_Background {
            get {
                return ResourceManager.GetString("Text_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking repository.
        /// </summary>
        internal static string Text_CheckingRepository {
            get {
                return ResourceManager.GetString("Text_CheckingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabeling boot start for.
        /// </summary>
        internal static string Text_DisablingBootStart {
            get {
                return ResourceManager.GetString("Text_DisablingBootStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading File.
        /// </summary>
        internal static string Text_DownloadingFile {
            get {
                return ResourceManager.GetString("Text_DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabeling boot start for.
        /// </summary>
        internal static string Text_EnabelingBootStart {
            get {
                return ResourceManager.GetString("Text_EnabelingBootStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching current application information....
        /// </summary>
        internal static string Text_FetchingApplicationInformation {
            get {
                return ResourceManager.GetString("Text_FetchingApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Definition.
        /// </summary>
        internal static string Text_HighDefinition {
            get {
                return ResourceManager.GetString("Text_HighDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Text_Installed {
            get {
                return ResourceManager.GetString("Text_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Text_Installing {
            get {
                return ResourceManager.GetString("Text_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string Text_MainButtonsExit {
            get {
                return ResourceManager.GetString("Text_MainButtonsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;More....
        /// </summary>
        internal static string Text_MainButtonsMore {
            get {
                return ResourceManager.GetString("Text_MainButtonsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string Text_MainButtonsNext {
            get {
                return ResourceManager.GetString("Text_MainButtonsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        internal static string Text_NotInstalled {
            get {
                return ResourceManager.GetString("Text_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connecto to repository server: {0}.
        /// </summary>
        internal static string Text_RepositoriesCheckCantConnectUrl {
            get {
                return ResourceManager.GetString("Text_RepositoriesCheckCantConnectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format or doesn&apos;t end with zip or xml for: {0}.
        /// </summary>
        internal static string Text_RepositoriesCheckInvalidURL {
            get {
                return ResourceManager.GetString("Text_RepositoriesCheckInvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository name given, name is required.
        /// </summary>
        internal static string Text_RepositoriesCheckNoName {
            get {
                return ResourceManager.GetString("Text_RepositoriesCheckNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repositories entered, need at least one repository..
        /// </summary>
        internal static string Text_RepositoriesCheckNoRepositories {
            get {
                return ResourceManager.GetString("Text_RepositoriesCheckNoRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name not unique for: {0}.
        /// </summary>
        internal static string Text_RepositoriesCheckNotUniqueName {
            get {
                return ResourceManager.GetString("Text_RepositoriesCheckNotUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting.
        /// </summary>
        internal static string Text_Restarting {
            get {
                return ResourceManager.GetString("Text_Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Definition.
        /// </summary>
        internal static string Text_StandardDefinition {
            get {
                return ResourceManager.GetString("Text_StandardDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string Text_Start {
            get {
                return ResourceManager.GetString("Text_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        internal static string Text_Started {
            get {
                return ResourceManager.GetString("Text_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string Text_Starting {
            get {
                return ResourceManager.GetString("Text_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State unknown.
        /// </summary>
        internal static string Text_StateUnknown {
            get {
                return ResourceManager.GetString("Text_StateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        internal static string Text_Stop {
            get {
                return ResourceManager.GetString("Text_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string Text_Stopped {
            get {
                return ResourceManager.GetString("Text_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string Text_Stopping {
            get {
                return ResourceManager.GetString("Text_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string Text_Uninstalling {
            get {
                return ResourceManager.GetString("Text_Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Text_Version {
            get {
                return ResourceManager.GetString("Text_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application suggestion.
        /// </summary>
        internal static string Tooltip_ApplicationSuggestionCaption {
            get {
                return ResourceManager.GetString("Tooltip_ApplicationSuggestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -140.
        /// </summary>
        internal static string Tooltip_ApplicationSuggestionHorizontalOffset {
            get {
                return ResourceManager.GetString("Tooltip_ApplicationSuggestionHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the lighttpd application.
        ///This application will give a performance boost to applications installed via CSI.
        ///
        ///Installing lighttpd is adviced!  (click here to close).
        /// </summary>
        internal static string Tooltip_ApplicationSuggestionText {
            get {
                return ResourceManager.GetString("Tooltip_ApplicationSuggestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=34VMUCF2K3WYW.
        /// </summary>
        internal static string URL_Donate {
            get {
                return ResourceManager.GetString("URL_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.networkedmediatank.com/showthread.php?tid=64695.
        /// </summary>
        internal static string URL_Help {
            get {
                return ResourceManager.GetString("URL_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.networkedmediatank.com/showthread.php?tid=64695.
        /// </summary>
        internal static string URL_Homepage {
            get {
                return ResourceManager.GetString("URL_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.nzbvortex.com.
        /// </summary>
        internal static string URL_NZBVortex {
            get {
                return ResourceManager.GetString("URL_NZBVortex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.networkedmediatank.com/showthread.php?tid=64695.
        /// </summary>
        internal static string URL_ReportBug {
            get {
                return ResourceManager.GetString("URL_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name, may only contain letters, numbers and spaces..
        /// </summary>
        internal static string Validate_InvalidWebserviceName {
            get {
                return ResourceManager.GetString("Validate_InvalidWebserviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid web address (URL), please verify and try again..
        /// </summary>
        internal static string Validate_InvalidWebserviceURL {
            get {
                return ResourceManager.GetString("Validate_InvalidWebserviceURL", resourceCulture);
            }
        }
    }
}
