//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.nmtinstaller.csi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pch-a110")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
            set {
                this["Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftpuser")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/installprepare.cgi")]
        public string InstallPrepareScriptURL {
            get {
                return ((string)(this["InstallPrepareScriptURL"]));
            }
            set {
                this["InstallPrepareScriptURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FileUploadRetries553 {
            get {
                return ((int)(this["FileUploadRetries553"]));
            }
            set {
                this["FileUploadRetries553"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/commands.zip")]
        public string CommandsScriptURL {
            get {
                return ((string)(this["CommandsScriptURL"]));
            }
            set {
                this["CommandsScriptURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apps/AppInit/appinit.cgi")]
        public string AppInitLocation {
            get {
                return ((string)(this["AppInitLocation"]));
            }
            set {
                this["AppInitLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/version")]
        public string CSIUpdateVersionURL {
            get {
                return ((string)(this["CSIUpdateVersionURL"]));
            }
            set {
                this["CSIUpdateVersionURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/update.zip")]
        public string CSIUpdateArchiveURL {
            get {
                return ((string)(this["CSIUpdateArchiveURL"]));
            }
            set {
                this["CSIUpdateArchiveURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/changelog")]
        public string CSIUpdateChangelogURL {
            get {
                return ((string)(this["CSIUpdateChangelogURL"]));
            }
            set {
                this["CSIUpdateChangelogURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://54.75.246.28/~csi/csi-downloads/appinit.cgi")]
        public string AppInitScriptURL {
            get {
                return ((string)(this["AppInitScriptURL"]));
            }
            set {
                this["AppInitScriptURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select")]
        public string UILanguage {
            get {
                return ((string)(this["UILanguage"]));
            }
            set {
                this["UILanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int ApplicationSuggestionDuration {
            get {
                return ((int)(this["ApplicationSuggestionDuration"]));
            }
            set {
                this["ApplicationSuggestionDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HardwareType {
            get {
                return ((string)(this["HardwareType"]));
            }
            set {
                this["HardwareType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HardwareName {
            get {
                return ((string)(this["HardwareName"]));
            }
            set {
                this["HardwareName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/cptjhmiller/CSI/master/csi-downloads/installpre" +
            "pare.cgi")]
        public string InstallPrepareScript2URL {
            get {
                return ((string)(this["InstallPrepareScript2URL"]));
            }
            set {
                this["InstallPrepareScript2URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPSubFolder {
            get {
                return ((string)(this["FTPSubFolder"]));
            }
            set {
                this["FTPSubFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebserverSubFolder {
            get {
                return ((string)(this["WebserverSubFolder"]));
            }
            set {
                this["WebserverSubFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/cptjhmiller/CSI/master/csi-downloads/version")]
        public string CSIUpdate2VersionURL {
            get {
                return ((string)(this["CSIUpdate2VersionURL"]));
            }
            set {
                this["CSIUpdate2VersionURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/cptjhmiller/CSI/master/csi-downloads/appinit.cg" +
            "i")]
        public string AppInitScript2URL {
            get {
                return ((string)(this["AppInitScript2URL"]));
            }
            set {
                this["AppInitScript2URL"] = value;
            }
        }
    }
}
